# mkdocs serve
site_name: Documentation for JLT project

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

# plugins:
#   - search
#   - mkdocstrings:
#       handlers:
#         python:
#           setup_commands:
#             - import sys
#             - sys.path.insert(0, "..")
nav:
  - Home: index.md
  - Code Reference:
    - utility: utility.md
    - calibrate: calibrate.md
    - input: input.md
    - main: main.md
  - Random generator:
    - Thoretical backgrond : random.md
  - JLT model:
    - Thoretical backgron : JLT_model.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
